sonar.projectKey=instamortgage-buyer
sonar.projectName=instamortgage-buyer
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/instamortgage-buyer/lcov.info
sonar.typescript.lcov.reportPaths=coverage/instamortgage-buyer/lcov.info

sonar.coverage.exclusions=**/*.spec.ts,**/*.config.ts,**/*.routes.ts,src/main.ts,src/environments/**,**/*.html,**/*.scss,**/*.css

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
