export const APPRO_STATUS = {
  PENDING: 'Pending',
  LEAD: 'Lead',
  IN_PROGRESS: 'In progress',
  AWAITING_BANK_APPROVAL: 'Awaiting Bank Approval',
  REJECTED: 'Rejected',
  NO_MATCH: 'No match',
  AWAITING_CUSTOMER_SELECTION: 'Awaiting Customer Selection',
  AWAITING_CUSTOMER_SIGNATURE: 'Awaiting Customer Signature',
  AIP_LETTER_READY: 'AIP Letter Ready',
  BANK_ONBOARDING_REJECTED: 'Bank Onboarding Rejected',
  EXPIRED: 'Expired',
  OFFERS_SELECTED: 'Offer selected',
  KFS_PENDING: 'KFS Pending',
} as const;

export type ApproStatus = (typeof APPRO_STATUS)[keyof typeof APPRO_STATUS];

export const TERMINAL_STATUSES: readonly string[] = [
  APPRO_STATUS.AWAITING_BANK_APPROVAL,
  APPRO_STATUS.REJECTED,
  APPRO_STATUS.BANK_ONBOARDING_REJECTED,
  APPRO_STATUS.AWAITING_CUSTOMER_SELECTION,
  APPRO_STATUS.AWAITING_CUSTOMER_SIGNATURE,
  APPRO_STATUS.AIP_LETTER_READY,
  APPRO_STATUS.OFFERS_SELECTED,
  APPRO_STATUS.EXPIRED,
  APPRO_STATUS.IN_PROGRESS,
  APPRO_STATUS.NO_MATCH,
];
